// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACH8CxmR2KtgGWOW7kI9zqD8l8vn6mQvk',
    appId: '1:180424503698:web:3e3f2db08562422fee914b',
    messagingSenderId: '180424503698',
    projectId: 'balanced-meal-3913c',
    authDomain: 'balanced-meal-3913c.firebaseapp.com',
    storageBucket: 'balanced-meal-3913c.firebasestorage.app',
    measurementId: 'G-GET8ZW627V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjJz7UxXzAQPgawR_ZaBTqvAAt8MdPWPc',
    appId: '1:180424503698:android:c1ce1e2f41abeb5aee914b',
    messagingSenderId: '180424503698',
    projectId: 'balanced-meal-3913c',
    storageBucket: 'balanced-meal-3913c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDht3m4QX3NEAOqSnxYXQYw2LlLu6muak',
    appId: '1:180424503698:ios:c164fda4c314abf3ee914b',
    messagingSenderId: '180424503698',
    projectId: 'balanced-meal-3913c',
    storageBucket: 'balanced-meal-3913c.firebasestorage.app',
    iosBundleId: 'com.example.balancedMeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDht3m4QX3NEAOqSnxYXQYw2LlLu6muak',
    appId: '1:180424503698:ios:c164fda4c314abf3ee914b',
    messagingSenderId: '180424503698',
    projectId: 'balanced-meal-3913c',
    storageBucket: 'balanced-meal-3913c.firebasestorage.app',
    iosBundleId: 'com.example.balancedMeal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACH8CxmR2KtgGWOW7kI9zqD8l8vn6mQvk',
    appId: '1:180424503698:web:6bb0e9f52c0d772aee914b',
    messagingSenderId: '180424503698',
    projectId: 'balanced-meal-3913c',
    authDomain: 'balanced-meal-3913c.firebaseapp.com',
    storageBucket: 'balanced-meal-3913c.firebasestorage.app',
    measurementId: 'G-11T7E2D36Q',
  );
}
